post http://localhost:3001/api/phones
Content-Type: application/json

{
    "name" : "Rssv",
    "phone" :55666666
}

###


GET http://localhost:3001/api/phones

###
DELETE http://localhost:3001/api/phones/61fabd2347d4237ed9f5fa45