post http://localhost:3000/api/numbers
Content-Type: application/json

{
    "name" : "Ropsfffy",
    "number" :5555555556666
}

###


GET http://localhost:3000/api/numbers

###
DELETE http://localhost:3000/api/numbers/61fabd2347d4237ed9f5fa45